### ISSUE TITLE
Database Flooding

### ISSUE THREAD

**Issue by deadbender** [knights-of-academia/pom-bot#3] opened 2020-09-29 18:13 UTC
For some reason, the bot currently floods the mySQL database and maxes out its connections. This causes it to go down until we can SSH into the server and restart it. Any fixes for this or ideas on fixing it would be greatly appreciated.

**Comment by rohitChaku** [comment] 2020-10-02 23:03
Hey, so, I believe the core problem that needs to be fixed is to find why that is happening. At present, I do not have that good of an understanding of the existing codebase to actually be able to solve it neither have I worked with mySQL extensively, so sorry about that. I can, however, add some suggestions to avoid manually restarting the service every time till the issue is fixed.

Maybe you might already be aware of this, but I think if you are using a Linux based Server you should be able to automatically restart the service in case it crashes.
I have ofter created a `systemd` service or simply used `cronjob` in similar situations.

I am not sure if this is aligned with the solution you are expecting, but I will add a couple of articles that you might find helpful if this is something you wish to follow while you work on the core problem:
1. [Linux Service using systemd](https://medium.com/@benmorel/creating-a-linux-service-with-systemd-611b5c8b91d6)
2. [Using Crontab](https://medium.com/@mhagemann/how-to-auto-restart-mysql-when-it-crashes-during-a-brute-force-attack-d7a03b726b7e)

**Comment by clayboone** [comment] 2020-10-05 22:04
Looks looks to be happening on [this line](https://github.com/knights-of-academia/pom-bot/blob/master/bot.py#L158).

The function is returning before closing the `cursor` and db connection.

**Closed** 2020-10-06 14:52 UTC
Labels: hacktoberfest
